opencodeiiita/UrbanVentures

UrbanVentures UX Journey/UserFlowDiag_swarupn17.txt

Issue: #1 
Description: 
This PR includes the user flow design for UrbanVentures, created in FigJam. The flow covers the onboarding process, preference setup, exploration of app features, user interactions, participation in challenges, tracking progress, and exit points. It ensures a logical and user-friendly experience for new users exploring the app for the first time. The FigJam file link is included for review.

Added User Flow Diagram link inside the UX Folder.

---

UrbanVentures UX Journey/UrbanVenture_UFD_Asheeesh9

Issue: #1 
Created UFD for Urban Ventures on Figjam

Created UFD for Urban Venture

---

UrbanVentures UX Journey/UrbanVentures_Puravi.txt

Issue: #1 
Added UFD link in a .txt file

Created UFD for UrbanVentures

---

UrbanVentures UX Journey/UFD_Snehalgupta-07.txt

Issue:#1
Created UFD and added FigJam link in .txt file

Created UFD

---

UrbanVentures UX Journey/UXVentures Heisenberg.txt

Create UXVentures Heisenberg.txt

---

UrbanVentures UX Journey/UFD_rndastech.txt

Created UFD_rndastech.txt

---

UX Laws/Skr-suyash.txt

Issue: #8 
Added the txt file (Skr-suyash.txt)

Added the required txt file

---

UX Laws/Apoorv012.txt

ux laws task

---

UX Laws/Task 2.txt

Create Task 2.txt

---

UX Laws/file.txt

Issue: #8 
Changed permissions regarding who can view the docs file

Added file.txt

---

UX Laws/PriyamJChakrabarty.txt

Added UX Laws

---

UX Laws/iking07.txt

UX Laws added

---

UX Laws/HGRgamer.txt

Issue: #8 
Complete UX Laws task

Complete UX Laws task

---

UX Laws/apexcoder.txt

Issue : #8 
added apexcoder.txt containing the Google Doc link

added apexcoder.txt

---

UrbanVentures UX Journey/UFD_HGRgamer.txt

Created UFD 

---

UrbanVentures UX Journey/UrbanVenturesoopshwet.txt

issue : #1 
Created UX using Figjam for UrbanVentures

FigJam link added 

---

UrbanVentures UX Journey/UrbanVenturesAtharwa23.txt

Created UserFlow

---

UX Laws/oopshwetairbnb.txt

issue : #8 
Added a google doc link which consists of UX Laws

UX Laws on AIRBNB Website

---

UX Laws/UX_laws_puravi.txt

Issue: #8 
Added google doc link in .txt file

Created UX_laws_puravi.txt

---

UX Laws/Asheeesh9.txt

Issue: #8 
Added .txt file in UX Laws folder

Added Instances of UX laws

---

UX Laws/kalim-Asim.txt

added link to ux laws doc

---

UrbanVentures UX Journey/UFD_iking07.txt

ISSUE: #1 
created the UFD with functionalities to be used.

UFD created

---

UrbanVentures UX Journey/UFD_shrut2606.txt

Userflow added

---

UX Fun Task/funtaskoopshwet.txt

Issue : #63 
Fun Task completed 
hihi boiii

Fun task Completed 

---

UX Fun Task/UX fun task.txt

Issue : #63 
completed the UX fun game and created a document by specifying importance of good UI/UX

completed the UX fun game

---

UX Fun Task/sanju26honey.txt

Issue: #63 
Completed UX Fun Task...

Completed UX Fun Task

---

UX Fun Task/shrut2606.txt

Doc file added

---

UX Fun Task/kalim-Asim_funTask.txt

Issue: #63 
task done , need tougher website to crack, this one was way too easy, (i am lying).

fun task completed

---

UX Fun Task/UX Fun Task_PHOX-9.txt

Issue: #63 
Uploaded the File for UX fun Task

Uploaded the UX Fun Task File

---

UX Fun Task/iking07.txt

ISSUE : #63 
Completed the really fun task

UX fun task completed

---

UX Fun Task/IIT2024013.txt

Issue: #63 
Added google doc link

Added google doc link 

---

UX Fun Task/Skr-suyash.txt

Issue: #63 
Added the required .txt file

Added my experience of the game

---

UX Fun Task/apexcoder007.txt

Issue : #63 
added google doc link inside apexcoder007.txt

added apexcoder007.txt

---

UX Fun Task/Darkknight0125.txt

Issue: #63 
added the docs link in text file.

Fun task done

---

Design Deja Vu - 1/Darkknight0125.txt

Issue: #52 
Added the figma link in txt file

Deja Vu done

---

Design Deja Vu - 1/PHOX-9.txt

Issue: #52 
Added Figma Link for Design Deja Vu

Added Figma link for Design Deja Vu

---

Design Deja Vu - 1/Asheeesh9.txt
UX Fun Task/Asheeesh9_funtask.txt

Issue: #52 
Replicated search bar

Created  Asheeesh9.txt

---

UX Fun Task/Asheeesh9_funtask.txt

Issue: #63 
Filled the form in 5:30 min :)

Created Asheeesh9_funtask.txt

---

Design Deja Vu - 1/Design Deja Vu - 1.txt

issue : #52 
created a search bar

Added Search bar

---

Design Deja Vu - 1/shrut2606.txt

Issue: #52 
Copied the image and added the link

Deja Vu Task-1

---

Design Deja Vu - 1/krishnamohan2006.txt

Issue: #52 
Replicated Search Bar

Replicated Search Bar

---

Design Deja Vu - 1/iking07.txt

Added the Deja-Vu task file

---

Design Deja Vu - 1/Puravi.txt

Issue: #52 
Created Puravi.txt, added figma link to search bar design in it

Created Puravi.txt

---

Design Deja Vu - 1/rajbir40.txt

issue : #52 
Search bar replicated

Search bar replicated

---

UX Fun Task/adityaagg4689.txt

issue: #63 
played the game and attached the google drive link

completed the game

---

Design Deja Vu - 1/adityaagg4689.txt

issue: #52 
replicated search bar and added the link to the figma file

replicated the search bar

---

Design Deja Vu - 1/SHARUKA-2005.txt

Created Dejavu

---

Design Deja Vu - 1/SearchBarOOPSHWET.txt

ISSUE : #52 
Replicated search Bar

SEARCH BAR ADDED 

---

UX Fun Task/krishnamohan2006.txt

Issue: #63 
Shared Google doc link

Shared Google Doc Link

---

Design Deja Vu - 1/prijitha.txt

ISSUE: #52 
Attached figma file

deja vu.txt

---

Design Deja Vu - 1/Kartikidejavu.txt

added file

---

UX Fun Task/SHARUKA-2005.txt

ISSUE: #63 
Added Google Doc link

Created Doc on UX Fun Task

---

Design Deja Vu - 1/Suvanwita.txt

Design Deja Vu-1

---

UX Fun Task/Puravi_funtask.txt

Issue: #63 
Completed the game in 9 mins

Created Puravi_funtask.txt

---

Design Deja Vu - 1/tamkap.txt

Issue: #52 
updated figma link

added link

---

UX Fun Task/IEC2024081.txt

Issue: #63 
added google docs link

UX fun task

---

Design Deja Vu - 1/HGRgamer.txt

Design Deja Vu

---

Design Deja Vu - 1/Snehalgupta-07.txt

Added Deja-Vu

---

UX Fun Task/prijitha ux.txt

ISSUE: #63 
Added Google document

prijitha ux.txt

---

UX Task-2/KunalKhandelwal1.txt

issue: #149 
Added Wireframes for the app urban venture

Added Wireframes

---

UX Task-2/Snehalgupta-07.txt

Wireframes

---

UX Task-2/iking07.txt

ISSUE : #149 
Added wireframe in figma

Added Wireframe

---

UX Task-2/Darkknight0125.txt

Issue: #149 
Added the figma link to text file

Task2 done

---

UX Task-2/puravimohta15.txt

Issue: #149 
Added link of design

Created wireframe

---

UX Task-2/shrut2606.xt

Issue: #149 
Wireframe created and figma link added

Wireframe added

---

UX Task-2/priji ux.txt

Create priji ux.txt

---

UX Task-2/PHOX-9.txt

Add Wireframe

---

Design Deja Vu - 2/rajbir40.txt

Design Deja Vu - 2

---

Design Deja Vu - 2/iking07.txt

Design Deja-vu 2

---

nomen06.txt

Design dejavu 2

---

Design Deja Vu - 2/puravi.txt

Issue: #162 
Used similar pictures as i couldnt find exact same

Design deja vu 2

---

Design Deja Vu - 2/Snehalgupta-07.txt

Deja -Vu - 2

---

Design Deja Vu - 2/YASMIN-SEKH.txt

Completed dejavu-2

---

Design Deja Vu - 3/Snehalgupta-07.txt

Deja -Vu - 3

---

UI Task 1 - UrbanVentures Onboarding/PHOX-9.txt

Onboarding pages

---

Design Deja Vu - 2/tamkap.txt

Issue : #162 
added design deja vu-2

Added deja vu-2

---

Design Deja Vu - 3/puravi.txt

Design deja vu 3

---

Design Deja Vu - 2/ashutosh.txt
Design Deja Vu - 3/official-ashutosh.txt

DejaVu - 3

---

Design Deja Vu - 3/SHARUKA-2005.txt

Create Dejavu 3

---

UI Task 1 - UrbanVentures Onboarding/Suvanwita.txt

Onboarding Screens

---

Design Deja Vu - 2/vishva.txt

Issue: #162 
Figma link is added

Figma Link added

---

Design Deja Vu - 2/prijiddv2.txt

prijiddv2.txt

---

Design Deja Vu - 3/prijiddv3.txt

prijiddv3.txt

---

UI Task 1 - UrbanVentures Onboarding/prijiob.txt

prijiob.txt

---

UI Task 1 - UrbanVentures Onboarding/Darkknight0125.txt

Issue: #182 
Added the figma and prototype link in a file.

Onboarding task

---

UI Task 1 - UrbanVentures Onboarding/iking07.txt

Added onboarding pages

---

Design Deja Vu - 4/tamkap.txt

Issue : #224 
added figma design link

design deja vu 4

---

Design Deja Vu - 4/PHOX-9.txt

Design Deja vu-4

---

UI Task 2 - Home Screen/PHOX-9.txt

Home Screen Urban Ventures

---

UI Task 2 - Home Screen/prijiuihomes.txt

prijiuihomes.txt

---

UI Task 2 - Home Screen/puravi.txt

Issue: #223 
Created home screen

home screen

---

Design Deja Vu - 4/rajbir40.txt

issue : #224 
added link to figma file

created design deja vu - 4

---

Design Deja Vu - 4/prijiddv4.txt

prijiddv4.txt

---

Enter the Arena/PriyamJChakrabarty.txt

New enter branch

---

UI Task 4/PriyamJChakrabarty.txt

UI Task 4 Done

---

UI Task 3/PriyamJChakrabarty.txt

UI task3 new
